services:
  - type: web
    name: big5-friends
    runtime: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_INSTANT_APP_ID
        value: fa1e83e0-aefe-4b75-8e07-741dcb678712
      - key: INSTANT_APP_ID
        value: fa1e83e0-aefe-4b75-8e07-741dcb678712
      - key: INSTANT_ADMIN_TOKEN
        value: 91bba977-5eb8-473d-8e83-0d3c50440e88
